export const GET_API = 'getApi'
export const GET_ARRAY_API = 'Get_Array_Api'
export const GET_ID_API = 'Get_Id_Api'
export const GET_CURRENT_API = 'getCurrentApi'
export const APPEND_API = 'appendApi'
export const EDIT_API = 'editApi'
export const DELETE_API = 'deleteApi'
